# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plotter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plotter
  pod 'FRDStravaClient', '~> 1.0.2'
  pod 'Polyline', '~> 4.0'
  pod 'SwiftLint'
end
